<h1>Quiz</h1>

<div class="row">
    <div class="col-12 border-top p-2">

        <form action="/quiz/answer" method="POST" id="quiz_form">

            <input type="hidden" name="selected_option" id="selected_option"/>

            <h3><?= htmlentities($question['question']['question'], ENT_QUOTES, 'UTF-8'); ?></h3>

            <div class="row">

                <?php foreach($question['options'] as $option): ?>
                    <div class="col-12 col-sm-6 p-2">
                        <button type="button" class="btn btn-lg w-100 answer-btn" data-option-id="<?= $option['id']; ?>">
                            <?= htmlentities($option['option'], ENT_QUOTES, 'UTF-8'); ?>
                        </button>
                    </div>
                <?php endforeach; ?>

            </div>

            <div class="row mb-3">
                <div class="col-12">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: <?= $userProgress['percentage_answered']; ?>%"
                             aria-valuenow="<?= $userProgress['percentage_answered']; ?>" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <button type="submit" class="btn btn-primary btn-lg w-100" id="submit_answer" disabled>Submit</button>
                </div>
            </div>

        </form>

    </div>
</div>

<script>
    let btns = document.querySelectorAll('.answer-btn');
    let toggleClass = 'btn-secondary';
    let isSubmitBtnEnabled = false;

    btns.forEach(function(buttonElement) {
        buttonElement.addEventListener('click', function(event) {
            let selectedId = event.target.getAttribute('data-option-id');
            document.getElementById('selected_option').setAttribute('value', selectedId);

            btns.forEach(function (buttonEl) {
                 buttonEl.classList.remove(toggleClass);
            });

            event.target.classList.toggle(toggleClass);

            if (!isSubmitBtnEnabled) {
                document.getElementById('submit_answer').removeAttribute('disabled');
            }
        });
    });
</script>
