<h1>Quizzes</h1>

<?php if(isset($flashMessage)): ?>
    <div class="alert alert-danger" role="alert">
        <?= $flashMessage; ?>
    </div>
<?php endif; ?>

<?php if(count($quizzesSelect) === 0): ?>
    <div class="row">
        <div class="col-12 border-top p-2">
            <h3>No quizzes available</h3>
        </div>
    </div>
<?php else: ?>
    <form action="/quiz/start" method="POST">
        <div class="form-group">
            <label for="inputName">Name</label>
            <input type="text" class="form-control" placeholder="Enter your name" id="inputName" name="name">
        </div>

        <div class="form-group">
            <label for="inputName">Quiz</label>
            <select class="custom-select" name="quiz_id">
                <option selected disabled>Select quiz</option>

                <?php foreach($quizzesSelect as $quiz): ?>
                    <option value="<?= $quiz['id']; ?>"><?= htmlentities($quiz['name'], ENT_QUOTES, 'UTF-8'); ?></option>
                <?php endforeach; ?>

            </select>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
<?php endif; ?>